<?php

/**
 * Class Awesomemediareport_Model_Awesomemediareport
 *
 * Awesome Media Report model
 */
class Awesomemediareport_Model_Awesomemediareport extends Kms_Module_BaseModel {
    /**
     * @var string Module name
     */
    const MODULE_NAME = 'awesomemediareport';

    /**
     * Init
     */
    public static function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Get access rules
     *
     * @return array
     */
    public function getAccessRules()
    {
        $accessRules[] = array(
            'controller' => 'awesomemediareport:report',
            'actions' => array('header', 'index', 'like', 'unlike'),
            'role' => Kms_Plugin_Access::PRIVATE_ROLE,
        );
        return $accessRules;
    }
}
